### PR TITLE
Adding AltspaceVR

### PR DESCRIPTION
**Pull request by GavanWilhite**
With a heavy heart, I submit this PR.

(the final line removal was automatically done by GitHub's editor. I can revert it if necessary)

### CODE REVIEW

**Comment by fabianoriccardi** [comment]
I have just push an update about AltSpaceVR, and I have just seen your PR... On wikipedia I see the release date was May 2015, but you write Jan 2015. Which is correct?

**Comment by GavanWilhite** [comment]
Depends a little on when you count, but we started holding events in
January:

https://www.roadtovr.com/altspacevr-open-beta-weekend-virtual-superbowl-party/

**Comment by fabianoriccardi** [comment]
Finally, I had merged your version since it was for sure written with enthusiast, thanks for the contribution!

**Comment by GavanWilhite** [comment]
Thanks Fabiano

**Pull request merged**
