### PR TITLE
add Sunrise Calendar

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by fabianoriccardi** [comment]
Thanks for the contribution! However I would propose 2 corrections: 

- I read on wiki that discontinuation date was on September 13, 2016, I think this is the most appropriate
- the description should be a single sentence, you may join them (Sunrise Calendar was a calendar application for web, mobile and desktop, featuring real-time aggregation of calendars from muliple sources)

**Comment by fabianoriccardi** [comment]
In "from muliple sources" you forgot a 't'

**Comment by adamralph** [comment]
@fabianoriccardi :+1: all fixed

**Comment by fabianoriccardi** [comment]
Great! 😁

**Pull request merged**
