### PR TITLE
Update adding Windows 10

### PR DESCRIPTION
**Pull request by SKApretto71**
Adding just Windows 10 as a soon to be killed product, as reaching EOS in Oct 2025.

### CODE REVIEW

**Comment by SKApretto71** [comment]
@fabianoriccardi please let me know if this is worth merging or I need to further enhance

**Comment by fabianoriccardi** [comment]
Hi, the commit is fine, but the graveyard, beyond Win 10, misses even Win XP, 7, 8, 8.1, 11 (since we already know that Win 12 will be released). This is because I see the Windows as a product which was born in 1985 (Windows 1.0), and, of course, it gets major releases over the years. 
I just put in this graveyard specific version of Windows with special purposes like Windows Essential Business Server 2008 which present specific features beyond a general-purpose OS.

This is my actual point of view, if you would comment I will listen your opinion.

**Comment by SKApretto71** [comment]
Hi Fabiano, I do get your point. Given the wide-spread adoption of Win10 (as Win7, WinXP and Win 3.1 that were key OS steps for end users) I had the idea to add it, and that older already dead OS were out of interest for visitors of the page. Win10 was announced as the last OS ever from Microsoft when launching the concept of servicing. The above to me sounds as the milestones, each introducing major - and breaking - changes.
I do not complain if you refuse do add, but if open to I can add the above key OS versions to the file.
BTW: I see a build failure that feels like an issue in the dependencies, so not related to the changes. In case it's part of the issue, let me know and I can remediate (did not tried to build it locally).

**Comment by SKApretto71** [comment]
@fabianoriccardi Following your approach and guidance, are then "Stream (classic)" - superseded by Stream for SharePoint, "Teams Live Events" - superseded by Team Town Halls and "Yammer" - superseded by Viva Engage valid entries?

**Comment by fabianoriccardi** [comment]
I remember when Microsoft presented Windows 10 *as the last OS ever*, but in hindsight, that was a great marketing presentation (we both remember that sentence after years, so they made an excellent job). But reality presents its toll, and as any other software, it needs new versions for different purposes: introducing breaking changes (especially about hardware requirements), introducing new identity, pushing the "new" product on marketing campaign and so on. In general, a new version helps users to clearly understand the difference between old and new version.

Probably this topic is subjective, but for now I would keep Windows far from the graveyard.

> older already dead OS were out of interest for visitors of the page

when I'm in historian mode, the early Windows are more interesting than modern one, and this was one of the points of why I started this site 🙃

> "Stream (classic)" - superseded by Stream for SharePoint, "Teams Live Events" - superseded by Team Town Halls and "Yammer" - superseded by Viva Engage 

They seem fine, if you would add these 3 elements you are welcome! Please open another PR.

**Pull request closed without merging**
